language: php
php:
  - "5.4"
  - "5.5"
  - "5.6"
  - "nightly"
before_script:
  - composer install

script:
  - phpenv config-rm xdebug.ini
  - mkdir -p build/logs
  - php vendor/bin/phpunit

after_script:
  - php vendor/bin/coveralls